---

- hosts: slaves
  tasks:
      - assert:
          that: (ansible_version.major, ansible_version.minor) >= (2, 0)
          msg: require ansible >= 2.0, found {{ansible_version.full}}

# Installation
- hosts: slaves
  tasks:
      - git:
          repo: git@github.com:DavidNemeskey/commoncrawl-downloader2.git
          dest: "{{ github_repo_dir }}"
          key_file: "{{ github_key_file }}"
          accept_hostkey: yes
        tags:
            - install
      - name: initialize virtualenv + install tmuxp
        pip: 
            name: tmuxp
            virtualenv: "{{ virtualenv_dir }}"
            virtualenv_python: python3
        tags:
            - install
      - name: install cc_corpus
        pip:
            name: "{{ github_repo_dir }}"
            virtualenv: "{{ virtualenv_dir }}"
            extra_args: "-e"
        tags:
            - install

# Cleanup

- hosts: slaves
  tasks:
      - file:
          path: "{{ virtualenv_dir }}"
          state: absent
        tags:
            - cleanup
      - file:
          path: "{{ github_repo_dir }}"
          state: absent
        tags:
            - cleanup
