---

# Installation
- hosts: slaves
  tasks:
      - git:
          repo: git@github.com:DavidNemeskey/commoncrawl-downloader2.git
          dest: "{{ github_repo_dir }}"
          key_file: "{{ github_key_file }}"
          accept_hostkey: yes
          version: master
        tags:
            - install
      - name: initialize virtualenv + upgrade setuptools and pip
        pip: 
            name:
              - setuptools>=40.0.0
              - pip>=19.0.0
            virtualenv: "{{ virtualenv_dir }}"
            virtualenv_python: python3
        tags:
            - install
      - name: install tmuxp
        pip: 
            name:
              - tmuxp
            virtualenv: "{{ virtualenv_dir }}"
            virtualenv_python: python3
        tags:
            - install
      - name: install cc_corpus
        pip:
            name: "{{ github_repo_dir }}"
            virtualenv: "{{ virtualenv_dir }}"
            extra_args: "-e"
        tags:
            - install

# Install emtsv
- hosts: slaves
  tasks:
      - name: install emtsv
        git:
          repo: git@github.com:DavidNemeskey/emtsv.git
          dest: "{{ emtsv_dir }}"
          key_file: "{{ github_key_file }}"
          accept_hostkey: yes
          version: quntoken_v1
        tags:
          - install_emtsv
      - name: install ctyhon
        pip:
            name:
              - cython
            virtualenv: "{{ virtualenv_dir }}"
        tags:
          - install_emtsv
      - name: install requirements for the submodules
        pip:
            name:
              - "{{ module }}/requirements.txt"
            virtualenv: "{{ virtualenv_dir }}"
            chdir: "{{ emtsv_dir }}"
            extra_args: "-r"
        loop:
          - emmorphpy
          - hunspellpy
          - purepospy
          - emdeppy
          - HunTag3
          - emudpipe
        loop_control:
          loop_var: module
        tags:
          - install_emtsv
      - name: download quntoken
        make:
          chdir: "{{ emtsv_dir }}/emtokenpy"
          target: all
        tags:
          - install_emtsv


# Clean up emtsv
- hosts: slaves
  tasks:
      - name: delete emtsv repo
        file:
          path: "{{ emtsv_dir }}"
          state: absent
        tags:
          - cleanup_emtsv


# Cleanup

- hosts: slaves
  tasks:
      - file:
          path: "{{ virtualenv_dir }}"
          state: absent
        tags:
            - cleanup
      - file:
          path: "{{ github_repo_dir }}"
          state: absent
        tags:
            - cleanup
