---

# Installation
- hosts: slaves
  tasks:
      - git:
          repo: git@github.com:DavidNemeskey/commoncrawl-downloader2.git
          dest: "{{ github_repo_dir }}"
          key_file: "{{ github_key_file }}"
          accept_hostkey: yes
          version: ansible-test
        tags:
            - install
      - name: initialize virtualenv + upgrade setuptools and pip
        pip: 
            name:
              - setuptools>=40.0.0
              - pip>=19.0.0
            virtualenv: "{{ virtualenv_dir }}"
            virtualenv_python: python3
        tags:
            - install
      - name: install tmuxp
        pip: 
            name:
              - tmuxp
            virtualenv: "{{ virtualenv_dir }}"
            virtualenv_python: python3
        tags:
            - install
      - name: install cc_corpus
        pip:
            name: "{{ github_repo_dir }}"
            virtualenv: "{{ virtualenv_dir }}"
            extra_args: "-e"
        tags:
            - install

# Cleanup

- hosts: slaves
  tasks:
      - file:
          path: "{{ virtualenv_dir }}"
          state: absent
        tags:
            - cleanup
      - file:
          path: "{{ github_repo_dir }}"
          state: absent
        tags:
            - cleanup
